paint/config/routes.rb
Rails.application.routes.draw do
  root "statics#home"
  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks'
  }
  resources :paintings
  resources :painters
  resources :comments
  get "comments", to: "comments#index"
  authenticated :user do
    root 'paintings#index', as: :authenticated_root
  end
  resources :users, only: [:index, :show, :edit ]
end

paint/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :painting
end

paint/app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :uid, :provider
  validates_presence_of :uid, scope: :provider

  def self.find_for_oauth(auth)
    find_or_create_by(uid: auth.uid, provider: auth.provider)
  end
end

paint/app/models/painter.rb
class Painter < ActiveRecord::Base
  has_many :paintings
  mount_uploader :image, PainterUploader
end

paint/app/models/painting.rb
class Painting < ActiveRecord::Base
  belongs_to :painter
  mount_uploader :image, PaintingUploader
end

paint/app/models/user.rb
class User < ActiveRecord::Base
  TEMP_EMAIL_PREFIX = 'change@me'

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  has_many :painters
  has_many :paintings
  has_many :identities, dependent: :destroy

  validates :username, presence: true

  def self.find_for_oauth(auth, signed_in_resource = nil)

    # Get the identity and user if they exist
    identity = Identity.find_for_oauth(auth)

    # If a signed_in_resource is provided it always overrides the existing user
    # to prevent the identity being locked with accidentally created accounts.
    # Note that this may leave zombie accounts (with no associated identity) which
    # can be cleaned up at a later date.
    user = signed_in_resource ? signed_in_resource : identity.user

    # Create the user if needed
    user = create_user(auth) if user.nil?

    # Associate the identity with the user if needed
    if identity.user != user
      identity.user = user
      identity.save!
    end

    # Return the user at the end of the method
    user
  end

  private
  def self.create_user(auth)
    # Get the existing user by email if the provider gives us a verified email.
    # If no verified email was provided we assign a temporary email and ask the
    # user to verify it on the next step via UsersController.finish_signup
    email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
    email = auth.info.email if email_is_verified

    # Select a user if they have already registered
    user = User.find_by_email(email) if email

    # Create the user if it's a new registration
    if user.nil?
      user = User.new(
        username: auth.info.nickname,
        image: auth.info.image || "",
        email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
        password: Devise.friendly_token[0,20]
      )
      # If you use confirmable module 
      # user.skip_confirmation!
      user.save!
    end

    # Return the user
    user
  end
end

paint/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected
    # my custom fields are :username, :image
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) do |u|
        u.permit(:username, :image, :remote_image_url, :email, :password, :password_confirmation)
      end

      devise_parameter_sanitizer.for(:account_update) do |u|
        u.permit(:username, :image, :remote_image_url, :email, :password, :password_confirmation, :current_password)
      end
    end
end

paint/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET 
  def index
    @posts = Post.all
  end

  # GET 
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # POST /comments
  def create
    @comment = current_user.comments.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # # PATCH/PUT /comments/1
  # def update
  #   respond_to do |format|
  #     if @comment.update(comment_params)
  #       format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @post }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @comment.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /comments/1
  # def destroy
  #   @comment.destroy
  #   respond_to do |format|
  #     format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

#     # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:title, :painting_id, :painting_rating, :comment, :user_id)
    end
end

paint/app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  PROVIDERS = [:instagram]

  PROVIDERS.each do |provider|
    define_method "#{provider}" do 

      # Store token into the session
      session[:access_token] = env["omniauth.auth"].credentials.token if env["omniauth.auth"].credentials.token

      @user = User.find_for_oauth(env["omniauth.auth"], current_user)

      if @user.persisted?
        sign_in_and_redirect @user, event: :authentication
        set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
      else
        session["devise.#{provider}_data"] = env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
    end
  end

end

paint/app/controllers/painters_controller.rb
class PaintersController < ApplicationController
  before_action :set_painting, only: [:show]

  # GET /painters
 def index
   @painters = Painter.all
 end

  # GET /painters/1
  def show
  end
end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_painter
      @painter = Painter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def painting_params
      params.require(:painter).permit(:painter_name, :image_url, :painter_yob, :painter_country, :painter_bio)
  end
end

paint/app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  before_action :set_painting, only: [:show]

  # GET /paintings
 def index
    flickr = Flickr.new(YAML.load_file(Rails.root.join('config', 'flickr.yml')))
    if params[:search]
      @paintings = flickr.photos.search(tags: params[:search]).take(10)
    else 
      @paintings = flickr.photos.search(tags: "manet")
    end
 end

  # GET /paintings/1
  def show
  end
end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_painting
      @painting = Painting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def painting_params
      params.require(:painting).permit(:painting_id, :painting_title, :painting_year, :image_url, :painting_location)
    end

paint/app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def home
  end
end

paint/app/controllers/users.controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

paint/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

paint/app/helpers/application_helper.rb
module ApplicationHelper
end

paint/app/helpers/comments_helper.rb
module CommentsHelper
end

paint/app/helpers/painters_helper.rb
module PaintersHelper
end

paint/app/helpers/paintings_helper.rb
module PaintingsHelper
end

paint/app/views/application/_header.html.erb
<header>
  <nav class="navbar navbar-default">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to root_path, class: "navbar-brand" do %>
          <span class="glyphicon glyphicon-heart" aria-hidden="true"></span> Paint
        <% end %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <form class="navbar-form navbar-left" role="search" method="get" action="/paintings">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search" name="search">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <% if current_user.image.present? %>
              <li><%= image_tag(current_user.image) %></li>
            <% end %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.username %> <span class="caret"></span></a>

              <ul class="dropdown-menu">
                <li><%= link_to "My Profile", current_user %></li>
                <li><%= link_to "Edit My Profile", edit_user_registration_path %></li>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li>
              <%= link_to "Sign up", new_user_registration_path %>
            </li>
            <li>
              <%= link_to "Sign in", new_user_session_path %>
            </li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->

  </nav>
</header>

paint/app/views/comments/_comment.html.erb
<li>
  <ul>
    <li><h1><%= link_to comment.title, comment %></h1> reviewed by <%= link_to comment.user.username, comment.user %></li>
  </ul>
</li>

paint/app/views/comments/_form.html.erb
<%= form_for :comment do |f| %>
  <p>
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

paint/app/views/comments/new.html.erb
<button>Add Comment</button>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

paint/app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Venue:</strong>
  <%= @post.venue.name %>
</p>

<p>
  <strong>Review:</strong>
  <%= @post.review %>
</p>


<p>
  <strong>Rating:</strong>
  <%= @post.rating %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user.username %>
</p>

<%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

paint/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Paint!</title>
 <link href='https://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="bootstrap.css" type="text/css" />
  <link rel="stylesheet" href="custom.css" type="text/css" />
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/masonry/3.3.2/masonry.pkgd.js"></script> 
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render "header" %>

  <% flash.each do |name, message| %>
    <div class="container alert alert-info alert-<%= name %>" role="alert">
      <%= message %>
    </div>  
  <% end %>

  <main class="container">
    <div class="large-12 columns">
      <%= yield %>
    </div>
  </main>

  

  <footer class="container">
    <nav>
      <ol class="breadcrumb">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", paintings_path %></li>
        <li><a href="">Contact</a></li>
        <li>&copy; 2015</li>
      </ol>
    </nav>
  </footer>
</body>
</html>

paint/app/views/painters/index.html.erb
<h1>Painters</h1>

<ul class="small-block-grid-2 medium-block-grid-3 large-block-grid-4">
  <%= render @painters %>
</ul>

paint/app/views/painters/show.html.erb
<%= image_tag @painter.image.url, width: 300 %>

<p>
  <strong>Name:</strong>
  <%= @painter.name %>
</p>

<p>
  <strong>Painter:</strong>
  <%= @painting.painter %>
</p>

<p>
  <strong>Years:</strong>
  <%= @painting.years %>
</p>

<p>
  <strong>Biography:</strong>
  <%= link_to @biography.painter.name, @painter.painter %>
</p>

<%= link_to 'Back', painters_path %>

paint/app/views/paintings/index.html.erb
<div class="container">
  <h2><%= @paintings.count %> Paintings found</h2>
  <div id="paintings">
    <% @paintings.each do |painting| %>
    <div class="col-sm-6 col-md-4 painting">
      <div class="thumbnail">
        <%= image_tag(painting.url(:medium)) %>
        <div class="caption">
          <div class="clear">
            <button type="button" class="btn btn-default btn-lg pull-right">
              <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
            </button>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

paint/app/views/paintings/show.html.erb
<%= image_tag @painting.image.url, width: 300 %>

<p>
  <strong>Title:</strong>
  <%= @painting.title %>
</p>

<p>
  <strong>Painter:</strong>
  <%= @painting.painter %>
</p>

<p>
  <strong>Year:</strong>
  <%= @painting.year %>
</p>

<p>
  <strong>Owner:</strong>
  <%= link_to @painting.painting.name, @painting.painting %>
</p>

<%= link_to 'Back', paintings_path %>

paint/app/views/statics/home.html.erb
<div class="jumbotron">
  <h1>Welcome to Paint!</h1>
  <br></br>
  <span></span>
  <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
</div>

<div class="home">
 <div>